import "./globals.css";
import { Poppins } from "next/font/google";
import SessionProviderWrapper from "./providers/SessionProviderWrapper";
import { ToastContainer } from "react-toastify";
import GlobalProvider from "@/components/application/GlobalProvider";

const PoppinsFont = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${PoppinsFont.className} antialiased`}>
        <SessionProviderWrapper>
          <GlobalProvider>
            <ToastContainer />
            {children}
          </GlobalProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
