import "./globals.css";
import { Poppins } from "next/font/google";
import SessionProviderWrapper from "./providers/SessionProviderWrapper";
import GlobalProvider from "@/components/application/GlobalProvider";
import { Toaster } from "react-hot-toast";

const PoppinsFont = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Kick Lifestyle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${PoppinsFont.className} antialiased`}>
        <SessionProviderWrapper>
          <GlobalProvider>
            <Toaster
              position="bottom-right"
              toastOptions={{
                duration: 5000,
                style: {
                  borderRadius: "8px",
                  padding: "12px 16px",
                  fontSize: "14px",
                },
              }}
            />
            {children}
          </GlobalProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
